Kermesse/Controllers/CategoriaGastoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Kermesse.Models;
using Microsoft.Reporting.WebForms;

namespace Kermesse.Controllers
{
    public class CategoriaGastoesController : Controller
    {
        private BDKermesseEntities db = new BDKermesseEntities();

        // GET: CategoriaGastoes
        [Authorize]
        public ActionResult Index(string dato)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }


            var catgast = from cg in db.CategoriaGastoes select cg;

            if (!string.IsNullOrEmpty(dato))
            {
                catgast = catgast.Where(cg => cg.nombreCategoria.Contains(dato) || cg.descripcion.Contains(dato));
            }

            return View(catgast.ToList());
        }

        // GET: CategoriaGastoes/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriaGasto categoriaGasto = db.CategoriaGastoes.Find(id);
            if (categoriaGasto == null)
            {
                return HttpNotFound();
            }
            return View(categoriaGasto);
        }

        // GET: CategoriaGastoes/Create
        [Authorize]
        public ActionResult Create()
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            return View();
        }

        // POST: CategoriaGastoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "idCatGasto,nombreCategoria,descripcion,estado")] CategoriaGasto categoriaGasto)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (ModelState.IsValid)
            {
                db.CategoriaGastoes.Add(categoriaGasto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(categoriaGasto);
        }

        // GET: CategoriaGastoes/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriaGasto categoriaGasto = db.CategoriaGastoes.Find(id);
            if (categoriaGasto == null)
            {
                return HttpNotFound();
            }
            return View(categoriaGasto);
        }

        // POST: CategoriaGastoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "idCatGasto,nombreCategoria,descripcion,estado")] CategoriaGasto categoriaGasto)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (ModelState.IsValid)
            {
                db.Entry(categoriaGasto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(categoriaGasto);
        }

        // GET: CategoriaGastoes/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoriaGasto categoriaGasto = db.CategoriaGastoes.Find(id);
            if (categoriaGasto == null)
            {
                return HttpNotFound();
            }
            return View(categoriaGasto);
        }

        // POST: CategoriaGastoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            CategoriaGasto categoriaGasto = db.CategoriaGastoes.Find(id);
            db.CategoriaGastoes.Remove(categoriaGasto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        public ActionResult VerReporte(string tipo)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "RptCategoriaGasto.rdlc");
            rpt.ReportPath = ruta;

            List<CategoriaGasto> ls = new List<CategoriaGasto>();

            ls = db.CategoriaGastoes.ToList();

            ReportDataSource rds = new ReportDataSource("DSCategoriaGasto", ls);

            rpt.DataSources.Add(rds);

            var b = rpt.Render(tipo, null, out mt, out enc, out f, out s, out w);

            return new FileContentResult(b, mt);
        }

    }
}

Kermesse/Views/CategoriaGastoes/Create.cshtml
@model Kermesse.Models.CategoriaGasto

@{
    ViewBag.Title = "Crear nueva categoría";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Crear nueva categoría</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Categoria de gastos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nombreCategoria, htmlAttributes: new { @class = "control-label col-md-2 mb-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombreCategoria, new { htmlAttributes = new { @class = "form-control mb-2", maxLength = "45" } })
                @Html.ValidationMessageFor(model => model.nombreCategoria, "", new { @class = "text-danger mb-2" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2 mb-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control mb-2", maxLength = "100" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger mb-2" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2 mb-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control mb-2", type = "number", min = "0", max = "1", @oninput = "onlyZeroOne(event)" } })
                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger mb-2" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <div style="margin-bottom: 1rem">
        <button type="button" class="btn btn-primary">
            @Html.ActionLink("Regresar", "Index", null, new { @style = "color: White;" })
        </button>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kermesse/Views/CategoriaGastoes/Delete.cshtml
@model Kermesse.Models.CategoriaGasto

@{
    ViewBag.Title = "Eliminar categoria de gasto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminar categoria de gastos</h2>

<h3>¿Estás seguro que quieres borrar esta categoría de gasto?</h3>
<div>
    <h4>Categoria de gastos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombreCategoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombreCategoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" /> |
            <button type="button" class="btn btn-primary">
                @Html.ActionLink("Regresar", "Index", null, new { @style = "color: White;" })
            </button>
        </div>
    }
</div>

Kermesse/Views/CategoriaGastoes/Details.cshtml
@model Kermesse.Models.CategoriaGasto

@{
    ViewBag.Title = "Detalles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles</h2>

<div>
    <h4>Categoria de gastos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombreCategoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombreCategoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

    </dl>
</div>
<p>
    <button type="button" class="btn btn-secondary">
        @Html.ActionLink("Editar", "Edit", new { id = Model.idCatGasto }, new { @class = "text-light" })
    </button>
    |
    <button type="button" class="btn btn-primary">
            @Html.ActionLink("Regresar", "Index", null, new { @style = "color: White;" })
    </button>
</p>

Kermesse/Views/CategoriaGastoes/Edit.cshtml
@model Kermesse.Models.CategoriaGasto

@{
    ViewBag.Title = "Editar Categoría de Gasto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Categoria de gastos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger mb-2" })
        @Html.HiddenFor(model => model.idCatGasto)

        <div class="form-group">
            @Html.LabelFor(model => model.nombreCategoria, htmlAttributes: new { @class = "control-label col-md-2 mb-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombreCategoria, new { htmlAttributes = new { @class = "form-control mb-2", maxLength = "45" } })
                @Html.ValidationMessageFor(model => model.nombreCategoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2 mb-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control mb-2", maxLength = "100" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger mb-2" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2 mb-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control mb-2", type = "number", min = "0", max = "1", @oninput = "onlyZeroOne(event)" } })
                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger mb-2" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-secondary"><i class="fa fa-pencil icon" style="margin-right: .5rem;"></i> Guardar</button>
            </div>
        </div>
    </div>
}

<div>
    <div style="margin-bottom: 1rem">
        <button type="button" class="btn btn-primary">
            @Html.ActionLink("Regresar", "Index", null, new { @style = "color: White;" })
        </button>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kermesse/Views/CategoriaGastoes/Index.cshtml
@model IEnumerable<Kermesse.Models.CategoriaGasto>

@{
    ViewBag.Title = "Categoría de gastos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Categoría de gastos</h2>

<div class="row mb-1">
    <div class="col-12 col-md-2 mb-1">
        <a class="btn btn-primary w-100" href="/CategoriaGastoes/Create">Crear</a>
    </div>
    <div class="col-12 col-md-2 mb-1">
        <div class="dropdown">
            <button class="btn btn-primary w-100"
                    type="button"
                    id="reportOptions"
                    data-bs-toggle="dropdown"
                    aria-expanded="false">
                Reporte
            </button>
            <ul class="dropdown-menu" aria-labelledby="reportOptions">
                <li>
                    <a class="dropdown-item"
                       href="/CategoriaGastoes/verReporte?tipo=PDF"
                       target="_blank">PDF</a>
                </li>
                <li>
                    <a class="dropdown-item"
                       href="/CategoriaGastoes/verReporte?tipo=Word">Word</a>
                </li>
                <li>
                    <a class="dropdown-item"
                       href="/CategoriaGastoes/verReporte?tipo=Excel">Excel</a>
                </li>
            </ul>
        </div>
    </div>

    <div class="col-12 col-md-8 col-lg-4 mb-1 ml-auto">
        @* BUSCAR *@
        @using (Html.BeginForm("Index", "CategoriaGastoes", FormMethod.Post, new { @class = "" }))
        {
            <div class="col-12 col-md-12 ">
                @Html.TextBox("dato", "", new { @class = "form-control rounded", placeholder = "Buscar" })
            </div>
        }
    </div>
</div>


<div class="table-responsive">
    <table class="table table-bordered table-striped table-hove">
        <thead class="table-info">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.nombreCategoria)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.descripcion)
                </th>
                <th>
                    Opciones
                </th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nombreCategoria)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>
                <td>
                    <a class="btn btn-secondary" href="@Url.Action("Edit", new { id = item.idCatGasto })">
                        <i class="fa fa-edit"></i>
                    </a>
                    <a class="btn btn-info" href="@Url.Action("Details", new { id = item.idCatGasto })">
                        <i class="fa fa-eye"></i>
                    </a>
                    <a class="btn btn-danger" href="@Url.Action("Delete", new { id = item.idCatGasto })">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
        }

    </table>

</div>