Kermesse/Controllers/ControlBonoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Kermesse.Models;
using Microsoft.Reporting.WebForms;

namespace Kermesse.Controllers
{
    public class ControlBonoesController : Controller
    {
        private BDKermesseEntities db = new BDKermesseEntities();

        // GET: ControlBonoes
        [Authorize]
        public ActionResult Index()
        {
            return View(db.ControlBonoes.ToList());
        }

        // GET: ControlBonoes/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ControlBono controlBono = db.ControlBonoes.Find(id);
            if (controlBono == null)
            {
                return HttpNotFound();
            }
            return View(controlBono);
        }

        // GET: ControlBonoes/Create
        [Authorize]
        public ActionResult Create()
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            Console.WriteLine("HELLO PUTO");
            return View();
        }

        // POST: ControlBonoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "idBono,nombre,valor,estado")] ControlBono controlBono)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            Console.WriteLine(controlBono);
            Console.WriteLine("HELLO PUTO");
            if (ModelState.IsValid)
            {
                db.ControlBonoes.Add(controlBono);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(controlBono);
        }

        // GET: ControlBonoes/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ControlBono controlBono = db.ControlBonoes.Find(id);
            if (controlBono == null)
            {
                return HttpNotFound();
            }
            return View(controlBono);
        }

        // POST: ControlBonoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "idBono,nombre,valor,estado")] ControlBono controlBono)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (ModelState.IsValid)
            {
                db.Entry(controlBono).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(controlBono);
        }

        // GET: ControlBonoes/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ControlBono controlBono = db.ControlBonoes.Find(id);
            if (controlBono == null)
            {
                return HttpNotFound();
            }
            return View(controlBono);
        }

        // POST: ControlBonoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            ControlBono controlBono = db.ControlBonoes.Find(id);
            db.ControlBonoes.Remove(controlBono);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        public ActionResult verReporte(string tipo)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "RptBonos.rdlc");
            rpt.ReportPath = ruta;

            List<ControlBono> ls = new List<ControlBono>();
            ls = db.ControlBonoes.ToList();

            ReportDataSource rd = new ReportDataSource("DSBonos", ls);
            rpt.DataSources.Add(rd);

            var b = rpt.Render(tipo, null, out mt, out enc, out f, out s, out w);
            return new FileContentResult(b, mt);
        }

        [Authorize]
        public ActionResult verReporteVertical(int? id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "RptBonosVertical.rdlc");
            rpt.ReportPath = ruta;

            ControlBono g = db.ControlBonoes.Find(id);
            List<ControlBono> ls = new List<ControlBono>();
            ls.Add(g);

            ReportDataSource rd = new ReportDataSource("DSBono", ls);
            rpt.DataSources.Add(rd);

            var b = rpt.Render("PDF", null, out mt, out enc, out f, out s, out w);
            return new FileContentResult(b, mt);
        }



    }
}

Kermesse/Views/ControlBonoes/Create.cshtml
@model Kermesse.Models.ControlBono

@{
    ViewBag.Title = "Creando nuevo bono";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Creando nuevo bono</h1>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2 mb-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control mb-2" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger mb-2" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.valor, htmlAttributes: new { @class = "control-label col-md-2 mb-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.valor, new { htmlAttributes = new { @class = "form-control mb-2", type = "number", step = "0.01", min = "0.00" } })
                @Html.ValidationMessageFor(model => model.valor, "", new { @class = "text-danger mb-2" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-12 col-md-6 col-lg-3 col-xl-2">
                <input type="submit" value="Crear" class="btn btn-success w-100" />
            </div>
            <div class="col-12 col-md-6 col-lg-3 col-xl-2">
                <a href="Index" class="btn btn-primary w-100">Regresar</a>
            </div>
        </div>
    </div>
}

Kermesse/Views/ControlBonoes/Delete.cshtml
@model Kermesse.Models.ControlBono

@{
    ViewBag.Title = "Eliminar bono";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminando bono</h1>

<h2>¿Estás seguro que quieres eliminar este bono?</h2>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.valor)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Eliminar" class="btn btn-danger" /> |
    <button type="button" class="btn btn-primary">
        @Html.ActionLink("Regresar", "Index", null, new { @class = "text-light" })
    </button>
</div>
    }
</div>

Kermesse/Views/ControlBonoes/Details.cshtml
@model Kermesse.Models.ControlBono

@{
    ViewBag.Title = "Detalles bono";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalles bono</h1>

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.valor)
        </dd>

    </dl>
</div>
<p>
    <button type="button" class="btn btn-secondary">
        @Html.ActionLink("Editar", "Edit", new { id = Model.idBono }, new { @class = "text-light" })
    </button>|
    <button type="button" class="btn btn-primary">
        @Html.ActionLink("Regresar", "Index", null, new { @class = "text-light" })
    </button>
</p>

Kermesse/Views/ControlBonoes/Edit.cshtml
@model Kermesse.Models.ControlBono

@{
    ViewBag.Title = "Editando bono";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editando bono</h1>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idBono)

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2 mb-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control mb-2" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger mb-2" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.valor, htmlAttributes: new { @class = "control-label col-md-2 mb-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.valor, new { htmlAttributes = new { @class = "form-control mb-2" } })
                @Html.ValidationMessageFor(model => model.valor, "", new { @class = "text-danger mb-2" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-12 col-md-6 col-lg-3 col-xl-2">
                <input type="submit" value="Guardar" class="btn btn-success w-100" />
            </div>
            <div class="col-12 col-md-6 col-lg-3 col-xl-2">
                <a href="../Index" class="btn btn-primary w-100">Regresar</a>
            </div>
        </div>
    </div>
}

Kermesse/Views/ControlBonoes/Index.cshtml
@model IEnumerable<Kermesse.Models.ControlBono>

@{
    ViewBag.Title = "Bonos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Bonos</h1>

<div class="row mb-1">
    <div class="col-12 col-md-2 mb-1">
        <a class="btn btn-primary w-100" href="/ControlBonoes/Create">Crear</a>
    </div>
    <div class="col-12 col-md-2 mb-1">
        <div class="dropdown">
            <button class="btn btn-primary w-100"
                    type="button"
                    id="reportOptions"
                    data-bs-toggle="dropdown"
                    aria-expanded="false">
                Reporte
            </button>
            <ul class="dropdown-menu" aria-labelledby="reportOptions">
                <li>
                    <a class="dropdown-item"
                       href="/ControlBonoes/verReporte?tipo=PDF"
                       target="_blank">PDF</a>
                </li>
                <li>
                    <a class="dropdown-item"
                       href="/ControlBonoes/verReporte?tipo=Word">Word</a>
                </li>
                <li>
                    <a class="dropdown-item"
                       href="/ControlBonoes/verReporte?tipo=Excel">Excel</a>
                </li>
            </ul>
        </div>
    </div>

    <div class="col-12 col-md-8 col-lg-4 mb-1 ml-auto">
        @* BUSCAR *@
        @using (Html.BeginForm("Index", "ControlBonoes", FormMethod.Post, new { @class = "" }))
        {
            <div class="col-12 col-md-12 ">
                @Html.TextBox("dato", "", new { @class = "form-control rounded", placeholder = "Buscar" })
            </div>
        }
    </div>
</div>

<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <thead class="table-info">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.valor)
                </th>
                <th>
                    Opciones
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.valor)
                    </td>
                    <td>
                        <a class="btn btn-secondary" href="@Url.Action("Edit", new { id = item.idBono })">
                            <i class="fa fa-edit"></i>
                        </a>
                        <a class="btn btn-info" href="@Url.Action("Details", new { id = item.idBono })">
                            <i class="fa fa-eye"></i>
                        </a>
                        <a class="btn btn-danger" href="@Url.Action("Delete", new { id = item.idBono })">
                            <i class="fa fa-trash"></i>
                        </a>
                        <a class="btn btn-primary" href="@Url.Action("verReporteVertical", new { id = item.idBono })" target="_blank">
                            <i class="fa fa-file-pdf-o"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>