Kermesse/Models/TasaCambio.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasaCambio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TasaCambio()
        {
            this.TasaCambioDets = new HashSet<TasaCambioDet>();
        }
    
        public int idTasaCambio { get; set; }
        public int monedaO { get; set; }
        public int monedaC { get; set; }
        public string mes { get; set; }
        public int anio { get; set; }
        public int estado { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual Moneda Moneda1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TasaCambioDet> TasaCambioDets { get; set; }
    }
}

Kermesse/Controllers/TasaCambiosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Kermesse.Models;
using Microsoft.Reporting.WebForms;

namespace Kermesse.Controllers
{
    public class TasaCambiosController : Controller
    {
        private BDKermesseEntities db = new BDKermesseEntities();

        // GET: TasaCambios
        [Authorize]
        public ActionResult Index(string dato)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            var tc = from m in db.VwTasaCambios select m;

            if (!string.IsNullOrEmpty(dato))
            {
                tc = tc.Where(m => m.mes.Contains(dato) || m.año.ToString().Contains(dato) || m.monedaO.ToString().Contains(dato) || m.monedaC.ToString().Contains(dato));
            }

            return View(tc.ToList());
        }

        // GET: TasaCambios/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TasaCambio tasaCambio = db.TasaCambios.Find(id);
            if (tasaCambio == null)
            {
                return HttpNotFound();
            }
            return View(tasaCambio);
        }

        // GET: TasaCambios/Create
        [Authorize]
        public ActionResult Create()
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            ViewBag.monedaO = new SelectList(db.Monedas, "idMoneda", "nombre");
            ViewBag.monedaC = new SelectList(db.Monedas, "idMoneda", "nombre");
            return View();
        }

        // POST: TasaCambios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create(TasaCambio tasaCambio)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (ModelState.IsValid)
            {
                TasaCambio ts = new TasaCambio();
                ts.monedaO = tasaCambio.monedaO;
                ts.monedaC = tasaCambio.monedaC;
                ts.mes = tasaCambio.mes;
                ts.anio = tasaCambio.anio;
                ts.estado = 1;
                db.TasaCambios.Add(ts);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.monedaO = new SelectList(db.Monedas, "idMoneda", "nombre", tasaCambio.monedaO);
            ViewBag.monedaC = new SelectList(db.Monedas, "idMoneda", "nombre", tasaCambio.monedaC);
            return View(tasaCambio);
        }

        // GET: TasaCambios/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TasaCambio tasaCambio = db.TasaCambios.Find(id);
            if (tasaCambio == null)
            {
                return HttpNotFound();
            }
            ViewBag.monedaO = new SelectList(db.Monedas, "idMoneda", "nombre", tasaCambio.monedaO);
            ViewBag.monedaC = new SelectList(db.Monedas, "idMoneda", "nombre", tasaCambio.monedaC);
            return View(tasaCambio);
        }

        // POST: TasaCambios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "idTasaCambio,monedaO,monedaC,mes,anio,estado")] TasaCambio tasaCambio)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (ModelState.IsValid)
            {
                tasaCambio.estado = 2;
                db.Entry(tasaCambio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.monedaO = new SelectList(db.Monedas, "idMoneda", "nombre", tasaCambio.monedaO);
            ViewBag.monedaC = new SelectList(db.Monedas, "idMoneda", "nombre", tasaCambio.monedaC);
            return View(tasaCambio);
        }

        // GET: TasaCambios/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TasaCambio tasaCambio = db.TasaCambios.Find(id);
            if (tasaCambio == null)
            {
                return HttpNotFound();
            }
            return View(tasaCambio);
        }

        // POST: TasaCambios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            TasaCambio tasaCambio = db.TasaCambios.Find(id);
            db.TasaCambios.Remove(tasaCambio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        public ActionResult verReporte(string tipo, string busq)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "RptTasaCambios.rdlc");
            rpt.ReportPath = ruta;

            List<VwTasaCambio> ls = new List<VwTasaCambio>();
            var ru = from m in db.VwTasaCambios select m;

            if (!string.IsNullOrEmpty(busq))
            {
                ru = ru.Where(m => m.monedaO.ToString().Contains(busq) || m.monedaC.Contains(busq) || m.mes.Contains(busq) || m.año.ToString().Contains(busq));
            }

            ls = ru.ToList();

            ReportDataSource rd = new ReportDataSource("DSTasaCambios", ls);
            rpt.DataSources.Add(rd);

            var b = rpt.Render(tipo, null, out mt, out enc, out f, out s, out w);
            return new FileContentResult(b, mt);
        }

        [Authorize]
        public ActionResult verReporteVertical(int? id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "RptTasaCambiosVertical.rdlc");
            rpt.ReportPath = ruta;

            VwTasaCambio i = db.VwTasaCambios.Find(id);
            List<VwTasaCambio> ls = new List<VwTasaCambio>();
            ls.Add(i);

            ReportDataSource rd = new ReportDataSource("DSTasaCambio", ls);
            rpt.DataSources.Add(rd);

            var b = rpt.Render("PDF", null, out mt, out enc, out f, out s, out w);
            return new FileContentResult(b, mt);
        }
    }
}

Kermesse/Views/TasaCambios/Create.cshtml
@model Kermesse.Models.TasaCambio

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Añadir</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TasaCambio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.monedaO, "Moneda de Origen", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("monedaO", null, htmlAttributes: new { @class = "form-control mb-2", @required = "required" })
                @Html.ValidationMessageFor(model => model.monedaO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.monedaC, "Moneda de Cambio", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("monedaC", null, htmlAttributes: new { @class = "form-control mb-2", @required = "required" })
                @Html.ValidationMessageFor(model => model.monedaC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mes, "Mes",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mes, new { htmlAttributes = new { @class = "form-control mb-2", @required = "required" } })
                @Html.ValidationMessageFor(model => model.mes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.anio, "Año", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.anio, new { htmlAttributes = new { @class = "form-control mb-2", @required = "required" } })
                @Html.ValidationMessageFor(model => model.anio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="margin-top: 1rem;">
                <button type="submit" value="Añadir" class="btn btn-success">
                    <i class="fa fa-plus icon" style="margin-right: .5rem;"></i>
                    Añadir
                </button>
                <button type="button" class="btn btn-info">
                    <i class="fa fa-arrow-left icon" style="margin-right: .5rem;"></i> @Html.ActionLink("Regresar", "Index", null, new { @style = "color: white;" })
                </button>
            </div>
        </div>
    </div>
}

Kermesse/Views/TasaCambios/Delete.cshtml
@model Kermesse.Models.TasaCambio

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TasaCambio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.mes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.anio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.anio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moneda.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Moneda.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moneda1.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Moneda1.nombre)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <button type="submit" value="Delete" class="btn btn-danger">
                <i class="fa fa-trash icon" style="margin-right: .5rem;"></i>
                Eliminar
            </button>
            <div class="btn btn-info">
                <i class="fa fa-arrow-left icon" style="margin-right: .5rem;"></i> @Html.ActionLink("Regresar", "Index", null, new { @style = "color: white;" })
            </div>
        </div>
    }
</div>

Kermesse/Views/TasaCambios/Details.cshtml
@model Kermesse.Models.TasaCambio

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalles</h2>

<div>
    <h4>TasaCambio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.mes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.anio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.anio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moneda.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Moneda.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Moneda1.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Moneda1.nombre)
        </dd>

    </dl>
</div>
<p>
    <div style="margin-bottom: 1rem">
        <button type="button" class="btn btn-secondary">
            <i class="fa fa-pencil icon" style="margin-right: .5rem;"></i> @Html.ActionLink("Editar", "Edit", new { id = Model.idTasaCambio }, new { @style = "color: white;" })
        </button>
        <div class="btn btn-info">
            <i class="fa fa-arrow-left icon" style="margin-right: .5rem;"></i> @Html.ActionLink("Regresar", "Index", null, new { @style = "color: white;" })
        </div>
    </div>
</p>

Kermesse/Views/TasaCambios/Edit.cshtml
@model Kermesse.Models.TasaCambio

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TasaCambio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idTasaCambio)

        <div class="form-group">
            @Html.LabelFor(model => model.monedaO, "monedaO", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("monedaO", null, htmlAttributes: new { @class = "form-control mb-2", @required = "required" })
                @Html.ValidationMessageFor(model => model.monedaO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.monedaC, "monedaC", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("monedaC", null, htmlAttributes: new { @class = "form-control mb-2", @required = "required" })
                @Html.ValidationMessageFor(model => model.monedaC, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mes, new { htmlAttributes = new { @class = "form-control mb-2", @required = "required" } })
                @Html.ValidationMessageFor(model => model.mes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.anio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.anio, new { htmlAttributes = new { @class = "form-control mb-2", @required = "required" } })
                @Html.ValidationMessageFor(model => model.anio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="margin-top: 1rem;">
                <button type="submit" value="Añadir" class="btn btn-secondary">
                    <i class="fa fa-pencil icon" style="margin-right: .5rem;"></i>
                    Guardar cambios
                </button>
                <button type="button" class="btn btn-info">
                    <i class="fa fa-arrow-left icon" style="margin-right: .5rem;"></i> @Html.ActionLink("Regresar", "Index", null, new { @style = "color: white;" })
                </button>
            </div>
        </div>
    </div>
}

Kermesse/Views/TasaCambios/Index.cshtml
@model IEnumerable<Kermesse.Models.VwTasaCambio>

@{
    ViewBag.Title = "Tasa cambio";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Tasa de cambio</h1>

<div class="row mb-1">
    <div class="col-12 col-md-2 mb-1">
        <a class="btn btn-primary w-100" href="/TasaCambios/Create">Crear</a>
    </div>
    <div class="col-12 col-md-2 mb-1">
        <div class="dropdown">
            <button class="btn btn-primary w-100"
                    type="button"
                    id="reportOptions"
                    data-bs-toggle="dropdown"
                    aria-expanded="false">
                Reporte
            </button>
            <ul class="dropdown-menu" aria-labelledby="reportOptions">
                <li>
                    <a href="#">@Html.ActionLink("PDF", "verReporte", new { tipo = "PDF", busq = Request.Form["dato"] }, new { @class = "dropdown-item", target = "_blank" })</a>
                </li>
                <li>
                    <a href="#">@Html.ActionLink("Word", "verReporte", new { tipo = "WORD", busq = Request.Form["dato"] }, new { @class = "dropdown-item", target = "_blank" })</a>
                </li>
                <li>
                    <a href="#">@Html.ActionLink("Excel", "verReporte", new { tipo = "EXCEL", busq = Request.Form["dato"] }, new { @class = "dropdown-item", target = "_blank" })</a>
                </li>
            </ul>
        </div>
    </div>

    <div class="col-12 col-md-8 col-lg-4 mb-1 ml-auto">
        @* BUSCAR *@
        @using (Html.BeginForm("Index", "TasaCambios", FormMethod.Post, new { @class = "" }))
        {
            <div class="col-12 col-md-12 ">
                @Html.TextBox("dato", "", new { @class = "form-control rounded", placeholder = "Buscar" })
            </div>
        }
    </div>
</div>

<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <thead class="table-info">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.mes)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.año)
                </th>
                <th>
                    Moneda origen
                </th>
                <th>
                    Moneda cambio
                </th>
                <th>
                    Opciones
                </th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.mes)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.año)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.monedaO)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.monedaC)
                    </td>
                    <td>
                        <a class="btn btn-secondary" href="@Url.Action("Edit", new { id = item.idTasaCambio })">
                            <i class="fa fa-edit"></i>
                        </a>
                        <a class="btn btn-info" href="@Url.Action("Details", new { id = item.idTasaCambio })">
                            <i class="fa fa-eye"></i>
                        </a>
                        <a class="btn btn-danger" href="@Url.Action("Delete", new { id = item.idTasaCambio })">
                            <i class="fa fa-trash"></i>
                        </a>
                        <a class="btn btn-primary" href="@Url.Action("verReporteVertical", new { id = item.idTasaCambio })" target="_blank">
                            <i class="fa fa-file-pdf-o"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>