Kermesse/Models/Opcion.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kermesse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opcion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opcion()
        {
            this.RolOpcions = new HashSet<RolOpcion>();
        }
    
        public int idOpcion { get; set; }
        public string opcionDescripcion { get; set; }
        public int estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolOpcion> RolOpcions { get; set; }
    }
}

Kermesse/Controllers/OpcionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Kermesse.Models;
using Microsoft.Reporting.WebForms;

namespace Kermesse.Controllers
{
    public class OpcionsController : Controller
    {
        private BDKermesseEntities db = new BDKermesseEntities();

        // GET: Opcions
        [Authorize]
        public ActionResult Index(string dato)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            var opcion = from o in db.Opcions select o;

            if (!string.IsNullOrEmpty(dato))
            {
                opcion = opcion.Where(o => o.opcionDescripcion.Contains(dato));
            }

            return View(opcion.ToList());
        }

        // GET: Opcions/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opcion opcion = db.Opcions.Find(id);
            if (opcion == null)
            {
                return HttpNotFound();
            }
            return View(opcion);
        }

        // GET: Opcions/Create
        [Authorize]
        public ActionResult Create()
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            return View();
        }

        // POST: Opcions/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "idOpcion,opcionDescripcion,estado")] Opcion opcion)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (ModelState.IsValid)
            {
                db.Opcions.Add(opcion);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(opcion);
        }

        // GET: Opcions/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opcion opcion = db.Opcions.Find(id);
            if (opcion == null)
            {
                return HttpNotFound();
            }
            return View(opcion);
        }

        // POST: Opcions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "idOpcion,opcionDescripcion,estado")] Opcion opcion)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (ModelState.IsValid)
            {
                db.Entry(opcion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(opcion);
        }

        // GET: Opcions/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Opcion opcion = db.Opcions.Find(id);
            if (opcion == null)
            {
                return HttpNotFound();
            }
            return View(opcion);
        }

        // POST: Opcions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            Opcion opcion = db.Opcions.Find(id);
            db.Opcions.Remove(opcion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize]
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        public ActionResult VerReporte(string tipo)
        {
            if (Session["UserID"] == null)
            {
                Session.Clear();
                FormsAuthentication.SignOut();
                return RedirectToAction("Login", "Account");
            }

            LocalReport rpt = new LocalReport();
            string mt, enc, f;
            string[] s;
            Warning[] w;

            string ruta = Path.Combine(Server.MapPath("~/Reportes"), "RptOpciones.rdlc");
            rpt.ReportPath = ruta;

            List<Opcion> ls = new List<Opcion>();

            ls = db.Opcions.ToList();

            ReportDataSource rds = new ReportDataSource("DSOpciones", ls);

            rpt.DataSources.Add(rds);

            var b = rpt.Render(tipo, null, out mt, out enc, out f, out s, out w);

            return new FileContentResult(b, mt);
        }
    }
}

Kermesse/Views/Opcions/Create.cshtml
@model Kermesse.Models.Opcion

@{
    ViewBag.Title = "Creando nueva opción";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Creando nueva opción</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Opcion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger mb-2" })
        <div class="form-group">
            @Html.LabelFor(model => model.opcionDescripcion, htmlAttributes: new { @class = "control-label col-md-2 mb-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.opcionDescripcion, new { htmlAttributes = new { @class = "form-control mb-2", maxLength = "70" } })
                @Html.ValidationMessageFor(model => model.opcionDescripcion, "", new { @class = "text-danger mb-2" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2 mb-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control mb-2", min = "0", @oninput = "onlyZeroOne(event)" } })
                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger mb-2" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-success " />
            </div>
        </div>
    </div>
}

<div>
    <div class="mb-1">
        <button type="button" class="btn btn-primary">
            @Html.ActionLink("Regresar", "Index", null, new { @class = "text-light" })
        </button>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kermesse/Views/Opcions/Delete.cshtml
@model Kermesse.Models.Opcion

@{
    ViewBag.Title = "Eliminando opción";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Eliminando opción</h2>

<h3>¿Estás seguro que quieres eliminar esta opción?</h3>
<div>
    <h4>Opcion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.opcionDescripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.opcionDescripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
    <input type="submit" value="Eliminar" class="btn btn-danger" /> |
    <button type="button" class="btn btn-primary">
        @Html.ActionLink("Regresar", "Index", null, new { @class = "text-light" })
    </button>
    </div>
    }
</div>

Kermesse/Views/Opcions/Details.cshtml
@model Kermesse.Models.Opcion

@{
    ViewBag.Title = "Mostrando opción";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Mostrando opción</h2>

<div>
    <h4>Opción</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.opcionDescripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.opcionDescripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estado)
        </dd>

    </dl>
</div>
<p>
    <button type="button" class="btn btn-secondary">
        @Html.ActionLink("Editar", "Edit", new { id = Model.idOpcion }, new { @class = "text-light" })
    </button>|
    <button type="button" class="btn btn-primary">
        @Html.ActionLink("Regresar", "Index", null, new { @class = "text-light" })
    </button>
</p>

Kermesse/Views/Opcions/Edit.cshtml
@model Kermesse.Models.Opcion

@{
    ViewBag.Title = "Editando opción";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editando opción</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Opcion</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger, mb-2" })
        @Html.HiddenFor(model => model.idOpcion)

        <div class="form-group">
            @Html.LabelFor(model => model.opcionDescripcion, htmlAttributes: new { @class = "control-label col-md-2 mb-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.opcionDescripcion, new { htmlAttributes = new { @class = "form-control mb-2", maxLength = "70" } })
                @Html.ValidationMessageFor(model => model.opcionDescripcion, "", new { @class = "text-danger mb-2" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2 mb-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.estado, new { htmlAttributes = new { @class = "form-control mb-2", min = "0", @oninput = "onlyZeroOne(event)" } })
                @Html.ValidationMessageFor(model => model.estado, "", new { @class = "text-danger mb-2" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-secondary"><i class="fa fa-pencil icon" style="margin-right: .5rem;"></i> Guardar</button>
            </div>
        </div>
    </div>
}

<div>
    <div class="mb-1">
        <button type="button" class="btn btn-primary">
            @Html.ActionLink("Regresar", "Index", null, new { @class = "text-light" })
        </button>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kermesse/Views/Opcions/Index.cshtml
@model IEnumerable<Kermesse.Models.Opcion>

@{ ViewBag.Title = "Opciones";
    Layout = "~/Views/Shared/_Layout.cshtml"; }

<h1>Opciones</h1>

<div class="row mb-1">
    <div class="col-12 col-md-2 mb-1">
        <a class="btn btn-primary w-100" href="/Opcions/Create">Crear</a>
    </div>
    <div class="col-12 col-md-2 mb-1">
        <div class="dropdown">
            <button class="btn btn-primary w-100"
                    type="button"
                    id="reportOptions"
                    data-bs-toggle="dropdown"
                    aria-expanded="false">
                Reporte
            </button>
            <ul class="dropdown-menu" aria-labelledby="reportOptions">
                <li>
                    <a class="dropdown-item"
                       href="/Opcions/verReporte?tipo=PDF"
                       target="_blank">PDF</a>
                </li>
                <li>
                    <a class="dropdown-item"
                       href="/Opcions/verReporte?tipo=Word">Word</a>
                </li>
                <li>
                    <a class="dropdown-item"
                       href="/Opcions/verReporte?tipo=Excel">Excel</a>
                </li>
            </ul>
        </div>
    </div>

    <div class="col-12 col-md-8 col-lg-4 mb-1 ml-auto">
        @* BUSCAR *@
        @using (Html.BeginForm("Index", "Opcions", FormMethod.Post, new { @class = "" }))
        {
            <div class="col-12 col-md-12 ">
                @Html.TextBox("dato", "", new { @class = "form-control rounded", placeholder = "Buscar" })
            </div>
        }
    </div>
</div>


<div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
        <thead class="table-info">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.opcionDescripcion)
                </th>
                <th>
                    Opciones
                </th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.opcionDescripcion)
                </td>
                
                <td>
                    <a class="btn btn-secondary" href="@Url.Action("Edit", new { id = item.idOpcion })">
                        <i class="fa fa-edit"></i>
                    </a>
                    <a class="btn btn-info" href="@Url.Action("Details", new { id = item.idOpcion })">
                        <i class="fa fa-eye"></i>
                    </a>
                    <a class="btn btn-danger" href="@Url.Action("Delete", new { id = item.idOpcion })">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
        }

    </table>
</div>